### ISSUE TITLE
How to deal with preprocess that change the number of points

### ISSUE THREAD

**Issue by lpatiny** [mljs/preprocess#1]
Just wondering if it is trivial or not ...

When you make a derivative for example you loose one point on the X scale and it would make sense to have a "centered" derivative where you remove one point and shift everything of half an interval.

This should be general for second derivative or any correlation (right term ?) vector.

**Comment by andcastillo** [comment]
You should not lose any point. For the first points you can use the progressive formula, for the intermediate points you should use the centered formulas and for the last points you can use the regressive formula. If you do like that you will have a more exact derivative in the borders and with the same number of points as the function.
Same for 2nd derivative.

**Comment by maasencioh** [comment]
this was closed in https://github.com/mljs/pad-array
